-- Add fake_answers field to questions table for storing AI-generated incorrect answers
ALTER TABLE questions
ADD COLUMN IF NOT EXISTS fake_answers JSONB;

COMMENT ON COLUMN questions.fake_answers IS 'Array of incorrect answers generated by AI or manually added';

